# Test Script for MongoDB

In [1]:
#Import Dependancies
import pandas as pd
import pymongo
from pymongo import MongoClient

In [6]:
# Connection string to MongoDB
conn='mongodb://localhost:27017'

# Making a Connection with MongoClient
client = MongoClient(conn)

# create database
db = client.deathDB

# create first collection
col_one = db.Heart_Failure_Records

# create second collection
col_two = db.Stroke_Records

In [5]:
# Read Heart Data into a DataFrame
heart_df = pd.read_csv('heart.csv')
heart_df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [7]:
# Read Stroke Data into a DataFrame
stroke_df = pd.read_csv('stroke.csv')
stroke_df = stroke_df.set_index('id')
stroke_df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
id,,,,,,,,,,,
9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [8]:
# Convert Heart Data to Dictionary and Push to MongoDB Collection
heart_dict = heart_df.to_dict('records')
col_one.insert_many(heart_dict)

ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 604989db6905b9ad6813ef86, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>

In [ ]:
# Convert Stroke Data to Dictionary and Push to MongoDB Collection
stroke_dict = stroke_df.to_dict('records')
col_two.insert_many(stroke_dict)

In [10]:
# Read a couple lines from heart collection in mongodb
# Display items in MongoDB collection
results = db.Heart_Failure_Records.find()

for result in results[:5]:
    print(result)

{'_id': ObjectId('60442696371d56b764e849e5'), 'age': 75.0, 'anaemia': 0, 'creatinine_phosphokinase': 582, 'diabetes': 0, 'ejection_fraction': 20, 'high_blood_pressure': 1, 'platelets': 265000.0, 'serum_creatinine': 1.9, 'serum_sodium': 130, 'sex': 1, 'smoking': 0, 'time': 4, 'DEATH_EVENT': 1}
{'_id': ObjectId('60442696371d56b764e849e6'), 'age': 55.0, 'anaemia': 0, 'creatinine_phosphokinase': 7861, 'diabetes': 0, 'ejection_fraction': 38, 'high_blood_pressure': 0, 'platelets': 263358.03, 'serum_creatinine': 1.1, 'serum_sodium': 136, 'sex': 1, 'smoking': 0, 'time': 6, 'DEATH_EVENT': 1}
{'_id': ObjectId('60442696371d56b764e849e7'), 'age': 65.0, 'anaemia': 0, 'creatinine_phosphokinase': 146, 'diabetes': 0, 'ejection_fraction': 20, 'high_blood_pressure': 0, 'platelets': 162000.0, 'serum_creatinine': 1.3, 'serum_sodium': 129, 'sex': 1, 'smoking': 1, 'time': 7, 'DEATH_EVENT': 1}
{'_id': ObjectId('60442696371d56b764e849e8'), 'age': 50.0, 'anaemia': 1, 'creatinine_phosphokinase': 111, 'diabetes': 0, 'ejection_fraction': 20, 'high_blood_pressure': 0, 'platelets': 210000.0, 'serum_creatinine': 1.9, 'serum_sodium': 137, 'sex': 1, 'smoking': 0, 'time': 7, 'DEATH_EVENT': 1}
{'_id': ObjectId('60442696371d56b764e849e9'), 'age': 65.0, 'anaemia': 1, 'creatinine_phosphokinase': 160, 'diabetes': 1, 'ejection_fraction': 20, 'high_blood_pressure': 0, 'platelets': 327000.0, 'serum_creatinine': 2.7, 'serum_sodium': 116, 'sex': 0, 'smoking': 0, 'time': 8, 'DEATH_EVENT': 1}

In [ ]:
# Read a couple lines from stroke collection in mongodb
# Display items in MongoDB collection
results = db.Stroke_Records.find()

for result in results[:5]:
    print(result)

In [12]:
client.close()